[phases.install]
aptPkgs = ["default-mysql-client", "pkg-config", "build-essential", "python3-dev", "libmariadb-dev-compat", "libmariadb-dev"]

[start]
cmd = "gunicorn dormitory.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile -"
